on:
  schedule:
    - cron:  '31 10,16,21 * * *'
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Update data
        run: npm install && npm run fetch

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          ([[ -n $(git status --porcelain) ]] && git commit -m "Update data" -a) || echo "nothing to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
